quotes/members/urls.py
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import path
from . import views

app_name = "members"

urlpatterns = [
    path("login_user", views.login_user, name="login"),
    path("logout_user", views.logout_user, name="logout"),
    path("register_user", views.register_user, name="register_user"),
    path("profile/", views.profile, name="profile"),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(
            template_name="authenticate/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="authenticate/password_reset_confirm.html",
            success_url="/members/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="authenticate/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("website.urls"), name="home"),
    path("members/", include("django.contrib.auth.urls")),
    path("members/", include("members.urls")),
]

quotes/members/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


# Extending User Model Using a One-To-One Link
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default="default_avatar.png", upload_to="profile_images")

    def __str__(self):
        return self.user.username

    # resizing images
    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.avatar.path)

        if img.height > 250 or img.width > 250:
            new_img = (250, 250)
            img.thumbnail(new_img)
            img.save(self.avatar.path)

quotes/members/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from .models import Profile


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100, required=True, widget=forms.TextInput())

    email = forms.CharField(max_length=100, required=True, widget=forms.TextInput())

    password1 = forms.CharField(
        max_length=50, required=True, widget=forms.PasswordInput()
    )

    password2 = forms.CharField(
        max_length=50, required=True, widget=forms.PasswordInput()
    )

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ["username", "password"]


class ProfileForm(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput())

    class Meta:
        model = Profile
        fields = ["avatar"]

quotes/members/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from .forms import RegisterForm, LoginForm, ProfileForm


def login_user(request):
    if request.user.is_authenticated:
        return redirect("/")

    if request.method == "POST":
        user = authenticate(
            username=request.POST["username"], password=request.POST["password"]
        )
        if user is None:
            messages.error(request, "Username or password didn't match")
            return redirect(to="members:login")

        login(request, user)
        return redirect(to="/")

    return render(request, "authenticate/login.html", context={"form": LoginForm()})


@login_required
def logout_user(request):
    logout(request)
    messages.success(request, ("Yoy Were Logged Out"))
    return redirect(to="/")


def register_user(request):
    if request.user.is_authenticated:
        return redirect(to="/")

    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="/")
        else:
            return render(
                request, "authenticate/register_user.html", context={"form": form}
            )

    return render(
        request, "authenticate/register_user.html", context={"form": RegisterForm()}
    )


@login_required
def profile(request):
    if request.method == "POST":
        profile_form = ProfileForm(
            request.POST, request.FILES, instance=request.user.profile
        )
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, "Your profile is updated successfully")
            return redirect(to="members:profile")

    profile_form = ProfileForm(instance=request.user.profile)
    return render(request, "authenticate/profile.html", {"profile_form": profile_form})


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = "authenticate/password_reset.html"
    email_template_name = "authenticate/password_reset_email.html"
    html_email_template_name = "authenticate/password_reset_email.html"
    success_url = reverse_lazy("members:password_reset_done")
    success_message = (
        "An email with instructions to reset your password has been sent to %(email)s."
    )
    subject_template_name = "authenticate/password_reset_subject.txt"

quotes/members/templates/authenticate/login.html
{% extends "website/base.html" %}

{% block content %}

{% if messages %}
{% for message in messages %}

    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
{% endfor %}
{% endif %}

<h1>Login</h1>

<form method="POST" action="">
    {% csrf_token %}
    <div class="mb-3">
      <label> Username:
        {{ form.username }}
    </label>
</div>

<div>
    <label>Password:
        {{ form.password }}
    </label>
</div>

<div class="grid">
    <button type="submit">Submit</button>
    <button type="reset" class="secondary">Reset</button>
</div>
<div class="small text-center">
    <a href="{% url 'members:password_reset' %}" class="text-center"><i>Forgot Password?</i></a>
</div>

</form>





{% endblock %}

quotes/members/templates/authenticate/password_reset.html
{% extends "website/base.html" %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

quotes/members/templates/authenticate/password_reset_complete.html
{% extends "website/base.html" %}

{% block content %}

    <h2>Password reset complete!</h2>

{% endblock %}

quotes/members/templates/authenticate/password_reset_confirm.html
{% extends "website/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

quotes/members/templates/authenticate/password_reset_done.html

{% extends "website/base.html" %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

quotes/members/templates/authenticate/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'members:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'members:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

quotes/members/templates/authenticate/register-user.html
{% extends "website/base.html" %}

{% block content %}

{% if form.errors %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        There Was An Errors With Your Form...
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>

{% endif %}

<h1>Register</h1>

<form method="POST" action="{% url 'members:register_user' %}">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <div>
        <label> Email:
            {{ form.email }}
        </label>
        <span>{{ form.errors.email }}</span>
    </div>
    <div>
        <label> Password:
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div>
        <label> Password confirmation:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>

</form>





{% endblock %}