quotes/members/urls.py
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import path
from . import views

app_name = "members"

urlpatterns = [
    path("login_user", views.login_user, name="login"),
    path("logout_user", views.logout_user, name="logout"),
    path("register_user", views.register_user, name="register_user"),
    path("profile/", views.profile, name="profile"),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(
            template_name="authenticate/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="authenticate/password_reset_confirm.html",
            success_url="/members/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="authenticate/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("website.urls"), name="home"),
    path("members/", include("django.contrib.auth.urls")),
    path("members/", include("members.urls")),
]

quotes/website/urls.py
from django.urls import path
from . import views

app_name = "website"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:page>", views.index, name="root_paginate"),
    path("bigbutton", views.bigbutton, name="bigbutton"),
    path("bigbutton_ok", views.bigbutton_ok, name="bigbutton_ok"),
    path("tags/", views.tags, name="tags"),
    path("authors/", views.authors, name="authors"),
    path("quotes/", views.quotes, name="quotes"),
    path("author/<int:author_id>", views.author, name="author"),
    path("tag/<str:tag_name>", views.tag, name="tag"),
]

quotes/website/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return f"{self.name}"


class Author(models.Model):
    fullname = models.CharField(max_length=50, unique=True)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=50)
    description = models.CharField(max_length=3000)

    def __str__(self):
        return f"{self.fullname}"


class Quotes(models.Model):
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    quote = models.CharField(max_length=250)

    def __str__(self):
        return f"{self.author} {self.quote} {self.tags}"

quotes/website/forms.py
from django.forms import (
    ModelForm,
    CharField,
    TextInput,
    DateField,
    ModelChoiceField,
    Select,
)
from .models import Tag, Author, Quotes


class TagForm(ModelForm):

    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())

    class Meta:
        model = Tag
        fields = ["name"]


class AuthorForm(ModelForm):

    fullname = CharField(min_length=3, max_length=50, required=True, widget=TextInput())
    born_date = CharField(
        min_length=6, max_length=25, required=True, widget=TextInput()
    )
    born_location = CharField(
        min_length=3, max_length=50, required=True, widget=TextInput()
    )
    description = CharField(
        min_length=10, max_length=3000, required=True, widget=TextInput()
    )

    class Meta:
        model = Author
        fields = ["fullname", "born_date", "born_location", "description"]


class QuoteForm(ModelForm):

    # author = CharField(min_length=3, max_length=50, required=True, widget=TextInput())
    author = ModelChoiceField(queryset=Author.objects.all(), widget=Select())
    quote = CharField(min_length=3, max_length=250, required=True, widget=TextInput())

    class Meta:
        model = Quotes
        fields = ["author", "quote"]
        exclude = ["tags"]

quotes/website/views.py
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from .models import Author, Quotes, Tag
from .forms import TagForm, AuthorForm, QuoteForm
from bs4 import BeautifulSoup
import json
import requests


def bigbutton_ok(request):
    return redirect(to="website:index")


def bigbutton(request):
    def scrappy_do(url):
        html_doc = requests.get(url)
        return BeautifulSoup(html_doc.text, "lxml")

    def quote_miner(quote):
        found_quote = {}
        tags_list = [tag.text for tag in quote.find_all("a", class_="tag")]
        found_quote["tags"] = tags_list
        found_quote["author"] = quote.find("small", class_="author").text
        found_quote["quote"] = (
            quote.find("span", class_="text").text.replace("“", "").replace("”", "")
        )

        return found_quote

    def scooby_do():
        url = "http://quotes.toscrape.com/page/"
        page = 1
        author_links = {}
        quotes_list = []
        soup = scrappy_do(url + f"{page}/")

        while (quotes := soup.find_all("div", class_="quote")) != []:
            for quote in quotes:
                quotes_list.append(quote_miner(quote))

            authors = soup.find_all("small", class_="author")
            a_links = [quote.find_all("a")[0]["href"] for quote in quotes]

            for i in range(len(a_links)):
                author_links[authors[i].text] = a_links[i]

            page += 1
            soup = scrappy_do(url + f"{page}/")

        return author_links, quotes_list

    def writer_info(links):
        authors_list = []
        url = "http://quotes.toscrape.com"
        for name in links:
            author = {}
            author["fullname"] = name
            result = scrappy_do(url + f"{links[name]}/")
            author["born_date"] = result.find("span", class_="author-born-date").text
            author["born_location"] = result.find(
                "span", class_="author-born-location"
            ).text
            author["description"] = result.find(
                "div", class_="author-description"
            ).text.strip()
            authors_list.append(author)

        return authors_list

    def check_len(string: str, length: int) -> str:
        if len(string) > length:
            return string[:length]
        return string

    def tags_save():
        deleted_tags = Tag.objects.all()
        deleted_tags.delete()
        with open("quotes.json", "r") as file:
            quotes = json.load(file)
        unique_tags = set()
        for item in quotes:
            for tag in item["tags"]:
                unique_tags.add(check_len(tag, 30))
        for item in unique_tags:
            tag = Tag(name=item)
            tag.save()

    def authors_save():
        deleted_authors = Author.objects.all()
        deleted_authors.delete()
        with open("authors.json", "r") as file:
            authors = json.load(file)
        for item in authors:
            author = Author(
                fullname=check_len(item["fullname"], 50),
                born_date=check_len(item["born_date"], 50),
                born_location=check_len(item["born_location"], 50),
                description=check_len(item["description"], 3000),
            )
            author.save()

    def quotes_save():
        deleted_quotes = Quotes.objects.all()
        deleted_quotes.delete()
        with open("quotes.json", "r") as file:
            quotes = json.load(file)
        i = 1
        for item in quotes:
            # tags = [Tag(name=tag) for tag in item["tags"]]
            clear_author = check_len(item["author"], 50)
            author = Author.objects.filter(fullname=clear_author)[:1]
            quote = Quotes(i, author[0].id, check_len(item["quote"], 250))
            i += 1
            quote.save()

            tags = Tag.objects.filter(name__in=item["tags"])
            # tags = [Tag(name=tag) for tag in item["tags"]]
            for tag in tags.iterator():
                quote.tags.add(tag)

    if request.method == "POST":
        author_links, quote_list = scooby_do()
        with open("quotes.json", "w") as fp:
            json.dump(quote_list, fp)
        with open("authors.json", "w") as fp:
            json.dump(writer_info(author_links), fp)
        tags_save()
        authors_save()
        quotes_save()
        return render(request, "website/bb_ok.html")

    return render(request, "website/bb.html")


# ------------------------------- The end of Scraper -----------------------------------


def ten_popular_tags():
    dict_tags = {}
    tags = Tag.objects.all()
    for tag in tags:
        quantity = Tag.objects.get(id=tag.id).quotes_set.all().count()
        dict_tags[tag.name] = quantity
    sorted_tuple_tags = sorted(dict_tags.items(), key=lambda x: x[1], reverse=True)[:10]
    top_tags = []
    for tag in sorted_tuple_tags:
        top_tags.append(tag[0])
    return top_tags


def index(request, page=1):
    quotes_list = Quotes.objects.all()
    ten_tags = ten_popular_tags()
    shift = 10

    paginator = Paginator(list(quotes_list), shift)
    if page > paginator.num_pages:
        return render(request, "website/404.html")
    quotes_on_page = paginator.page(page)

    return render(
        request,
        "website/index.html",
        {"quotes": quotes_on_page, "ten_popular_tags": ten_tags},
    )


def author(request, author_id):
    author = Author.objects.get(pk=author_id)
    return render(request, "website/author.html", context={"author": author})


def tag(request, tag_name):
    # It's need to push also Quotes with tag_id !
    # tag = Tag.objects.get(name=tag_name)
    quotes = Tag.objects.get(name=tag_name).quotes_set.all()
    return render(
        request, "website/tag.html", context={"tag": tag_name, "quotes": quotes}
    )


@login_required
def tags(request):
    if request.method == "POST":
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="website:index")
        else:
            return render(request, "website/tags.html", {"form": form})

    return render(request, "website/tags.html", {"form": TagForm()})


@login_required
def authors(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="website:index")
        else:
            return render(request, "website/authors.html", {"form": form})

    return render(request, "website/authors.html", {"form": AuthorForm()})


@login_required
def quotes(request):
    tags = Tag.objects.all()
    authors = Author.objects.all()
    quote_id = Quotes.objects.all().count()

    if request.method == "POST":
        form = Quotes(quote_id + 1, request.POST["author"], request.POST["quote"])
        # if form.is_valid():
        form.save()

        choice_tags = Tag.objects.filter(name__in=request.POST.getlist("tags"))
        for tag in choice_tags.iterator():
            form.tags.add(tag)

        return redirect(to="website:index")
    # else:
    # return render(
    #     request,
    #     "website/quotes.html",
    #     {"tags": tags, "form": QuoteForm()},
    # )

    return render(
        request,
        "website/quotes.html",
        {"tags": tags, "form": QuoteForm()},
    )

quotes/website/templates/website/author.html
{% extends "website/base.html" %}

{% block content %}
<div class="author-details">
    <h3 class="author-title">{{author.fullname}}</h3>
    <p><strong>Born:</strong> <span class="author-born-date">{{author.born_date}}</span> <span class="author-born-location">
            {{author.born_location}}</span></p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{author.description}}
    </div>
</div>
{% endblock %}

quotes/website/templates/website/authors.html
{% extends "website/base.html" %}

{% block content %}

<form method="POST" action="{% url 'website:authors' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the Author fullname:
            {{form.fullname}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter author's born date:
            {{form.born_date}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter author's born location:
            {{form.born_location}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the author's description:
            {{form.description}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes/website/templates/website/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Note information</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'website/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/main.css' %}">
</head>
<body>
    <div class="container">
        <div class="row header-box">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Great quotes from great people</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                    {% if user.is_authenticated %}
                        <button class="btn btn-sm btn-primary w-100 ml-2" onclick="location.href='{% url 'website:bigbutton' %}'">Big Secret Button</button>
                        <button class="btn btn-sm btn-primary w-100 ml-2" onclick="location.href='{% url 'website:authors' %}'">Add a new Author</button>
                        <button class="btn btn-sm btn-primary w-100 ml-2" onclick="location.href='{% url 'website:quotes' %}'">Add a new Quote</button>
                        <button class="btn btn-sm btn-primary w-100 ml-2" onclick="location.href='{% url 'website:tags' %}'">Add a new Tag</button>
                        <button class="btn btn-sm btn-primary w-100 ml-2" onclick="location.href='{% url 'members:logout' %}'">Logout</button>
                    {% else %}
                    <button class="btn btn-sm btn-primary w-100 ml-2" onclick="location.href='{% url 'members:register_user' %}'">Register</button>
                    <button class="btn btn-sm btn-primary w-100 ml-2" onclick="location.href='{% url 'members:login' %}'">Login</button>

                    {% endif %}
                </p>
            </div>
        </div>

    {% block content %} {% endblock %}

</body>
</html>

quotes/website/templates/website/bb.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Scrapy DB</title>
    
    <style>
        body {
            background-color: black;
            font-family: sans-serif;
            margin: 0;
            padding: 0;
        }
        .button {
            display: block;
            margin: 25%;
            width: 50%;
            height: 250px;
            line-height: 50px;
            text-align: center;
            font-size: 40px;
            font-weight: bold;
            color: white;
            background-color: #0172ad;
            border: none;
            cursor: pointer;
        }
        .button:hover {
            background-color: #005789;
        }
    </style>
</head>
<body>
    <form method="POST" action="{% url 'website:bigbutton' %}">
        {% csrf_token %}
        <button class="button">Scrapy DB</button>
</form>
</body>
</html>

quotes/website/templates/website/bb_ok.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Scrapy DB</title>
    
    <style>
        body {
            background-color: black;
            font-family: sans-serif;
            margin: 0;
            padding: 0;
        }
        .button {
            display: block;
            margin: 25%;
            width: 50%;
            height: 250px;
            line-height: 50px;
            text-align: center;
            font-size: 40px;
            font-weight: bold;
            color: rgb(236, 203, 13);
            background-color: #0172ad;
            border: none;
            cursor: pointer;
        }
        .button:hover {
            background-color: #005789;
        }
    </style>
</head>
<body>
    <form method="POST" action="{% url 'website:bigbutton_ok' %}">
        {% csrf_token %}
        <button class="button">Scraping well done!</button>
</form>
</body>
</html>

quotes/website/templates/website/index.html
{% extends "website/base.html" %}
{% load filters %}


{% block content %}
<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author_id|author}}</small>
                <a href="/author/{{quote.author_id}}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote|tags %}
                <a class="tag" href="/tag/{{tag.name}}">{{tag.name}}</a>
                {% endfor %}
            </div>

        </div>
        {% endfor %}
        <nav>
            <ul class="pager">
                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                    href="{% if quotes.has_previous %} {% url 'website:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                    <span aria-hidden="true">←</span>Previous</a>
                </li>
                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}"
                    href="{% if quotes.has_next %} {% url 'website:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                    Next <span aria-hidden="true">→</span></a>
                </li>
            </ul>
        </nav>
    </div>


    <div class="col-md-4 tags-box">
        
        <h2>Top Ten tags</h2>
        {% for tag_name in ten_popular_tags %}
        <span class="tag-item">
            <a class="{% cycle 'tag10' 'tag9' 'tag8' 'tag7' 'tag6' 'tag5' 'tag4' 'tag3' 'tag2' 'tag1'%}" href="/tag/{{tag_name}}">{{tag_name}}</a>
        </span>

        {% endfor %}
    </div>
</div>

{% endblock %}

quotes/website/templates/website/quotes.html
{% extends "website/base.html" %}

{% block content %}

<form method="POST" action="{% url 'website:quotes' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Author:
            {{ form.author }}

        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div style="padding: 10px">
        <label> Quote:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

quotes/website/templates/website/tag.html
{% extends "website/base.html" %}
{% load filters %}


{% block content %}
<H1>Quotes with tag {{tag}}</H1>
<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author_id|author}}</small>
                <a href="/author/{{quote.author_id}}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote|tags %}
                <a class="tag" href="/tag/{{tag.name}}">{{tag.name}}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>    
{% endblock %}

quotes/website/templates/website/tags.html
{% extends "website/base.html" %}

{% block content %}

<form method="POST" action="{% url 'website:tags' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}